services:
  gserver:
    build:
      dockerfile: server/Dockerfile
    container_name: gserver
    ports:
      - "8182:8182"
    volumes:
      - ${PWD}/server/air-routes.groovy:/opt/gremlin-server/scripts/air-routes.groovy
      - ${PWD}/data/air-routes.graphml:/opt/gremlin-server/data/air-routes.graphml
  utils:
    profiles: ["utils"]
    container_name: utils
    image: oven/bun:1.0.13
    network_mode: host
    volumes:
      - ${PWD}/utils:/home/bun/app
      - ${PWD}/node_modules:/home/bun/app/node_modules
      - ${PWD}/bun.lockb:/home/bun/app/bun.lockb
    depends_on:
      gserver:
        condition: service_started
        restart: true
  gconsole:
    profiles: ["console"]
    image: tinkerpop/gremlin-console:3.6.2
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: gconsole
    network_mode: host
    depends_on:
      gserver:
        condition: service_started
        restart: true
    volumes:
      - ${PWD}/console/air-routes.groovy:/opt/gremlin-console/scripts/air-routes.groovy
      - ${PWD}/console/remote.yaml:/opt/gremlin-console/conf/remote.yaml
      - ${PWD}/data/air-routes.graphml:/opt/gremlin-console/data/air-routes.graphml
