#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

# to force use of bun requires bun to implement more node APIs
# bunx --bun lint-staged --concurrent false
bunx lint-staged --concurrent false
